package gpu

// type Autogenerated struct {
// 	Gpu Gpu `json:"gpu"`
// }

type Gpu struct {
	Cards []Cards `json:"cards"`
}

type Cards struct {
	Address string `json:"address"`
	Index   int    `json:"index"`
	Pci     Pci    `json:"pci"`
}

type Pci struct {
	Driver               string               `json:"driver"`
	Address              string               `json:"address"`
	Vendor               Vendor               `json:"vendor"`
	Product              Product              `json:"product"`
	Revision             string               `json:"revision"`
	Subsystem            Subsystem            `json:"subsystem"`
	Class                Class                `json:"class"`
	Subclass             Subclass             `json:"subclass"`
	ProgrammingInterface ProgrammingInterface `json:"programming_interface"`
}

type ProgrammingInterface struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Subclass struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Class struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Subsystem struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Product struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Vendor struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
